# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.935768 on dev /home/miguel/Documentos/TA/exercices/ex6/train/development.clean.es
# We were before running iteration 6
# finished dom 25 dic 2022 13:12:16 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex6/train/work/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=4 type=wbe-monotonicity-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/train/work/model/reordering-table.wbe-monotonicity-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.00620543 0.0418344 0.16222 0.11617
Distortion0= 0.0230045
LM0= 0.171831
WordPenalty0= 0.0419032
PhrasePenalty0= 0.00280805
TranslationModel0= 0.138203 0.10166 0.109087 -0.0850732
UnknownWordPenalty0= 1
