# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.93299 on dev /home/miguel/Documentos/TA/exercices/ex6/train/development.clean.es
# We were before running iteration 2
# finished dom 25 dic 2022 13:07:43 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=4 type=wbe-monotonicity-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/reordering-table.wbe-monotonicity-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.242514 0.0600033 0.00996281 0.0381254
Distortion0= 0.0518092
LM0= 0.216406
WordPenalty0= 0.000699918
PhrasePenalty0= -0.081275
TranslationModel0= 0.108909 0.0429138 0.117471 -0.0299112
UnknownWordPenalty0= 1
