# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.934992 on dev /home/miguel/Documentos/TA/exercices/ex6/train/development.clean.es
# We were before running iteration 3
# finished dom 25 dic 2022 13:08:49 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=4 type=wbe-monotonicity-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/reordering-table.wbe-monotonicity-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.0976786 0.0733433 0.109679 0.0165097
Distortion0= 0.0973368
LM0= 0.194376
WordPenalty0= -0.0836445
PhrasePenalty0= -0.0581985
TranslationModel0= 0.168016 0.0256662 0.0741276 -0.00142411
UnknownWordPenalty0= 1
