# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.934374 on dev /home/miguel/Documentos/TA/exercices/ex6/train/development.clean.es
# We were before running iteration 4
# finished dom 25 dic 2022 13:09:58 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=4 type=wbe-monotonicity-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/reordering-table.wbe-monotonicity-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.129562 0.0734256 0.0783769 0.0497321
Distortion0= 0.0312464
LM0= 0.175082
WordPenalty0= 0.0209103
PhrasePenalty0= -0.0727436
TranslationModel0= 0.132064 0.100021 0.0816179 -0.0552178
UnknownWordPenalty0= 1
