# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.934788 on dev /home/miguel/Documentos/TA/exercices/ex6/train/development.clean.es
# We were before running iteration 5
# finished dom 25 dic 2022 13:11:05 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=4 type=wbe-monotonicity-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/mert-work/filtered/reordering-table.wbe-monotonicity-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex6/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.0481476 0.0962632 0.167034 0.0772031
Distortion0= 0.00347117
LM0= 0.167681
WordPenalty0= 0.0195791
PhrasePenalty0= -0.0850478
TranslationModel0= 0.121273 0.0948056 0.0697729 -0.0497215
UnknownWordPenalty0= 1
