# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.935208 on dev /home/miguel/Documentos/TA/exercices/ex5/train/development.clean.es
# We were before running iteration 3
# finished dom 25 dic 2022 12:54:07 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex5/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex5/mert-work/filtered/reordering-table.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex5/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.0455171 0.0209782 0.101359 0.0114447 0.108302 0.069267
Distortion0= -0.0104118
LM0= 0.22454
WordPenalty0= -0.0333323
PhrasePenalty0= -0.0335139
TranslationModel0= 0.137095 0.0862105 0.0892336 -0.0287937
UnknownWordPenalty0= 1
