# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.935635 on dev /home/miguel/Documentos/TA/exercices/ex5/train/development.clean.es
# We were before running iteration 4
# finished dom 25 dic 2022 12:55:25 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex5/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex5/mert-work/filtered/reordering-table.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex5/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.028478 0.0107125 0.0258278 0.160609 0.207748 0.0161183
Distortion0= 0.0109356
LM0= 0.166896
WordPenalty0= -0.00473952
PhrasePenalty0= -0.0489312
TranslationModel0= 0.17802 0.0580234 0.0546818 -0.02828
UnknownWordPenalty0= 1
