# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.916518 on dev /home/miguel/Documentos/TA/exercices/ex4/train/development.clean.es
# We were before running iteration 6
# finished dom 25 dic 2022 12:24:14 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex4/train/work/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/train/work/model/reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.123960733983451 0.0181534582047187 0.0968105965148535 0.081180000631491 0.0657104588195874 0.0350475133370666
Distortion0= 0.0616761537456365
LM0= 0.166537067847189
WordPenalty0= 0.0243035763468276
PhrasePenalty0= -0.0861587585936265
TranslationModel0= 0.0863528188081251 0.0326801377859336 0.0830426605591781 0.0383860648223152
UnknownWordPenalty0= 1
