# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.915512 on dev /home/miguel/Documentos/TA/exercices/ex4/train/development.clean.es
# We were before running iteration 3
# finished dom 25 dic 2022 12:22:38 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex4/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/mert-work/filtered/reordering-table.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.125586225230679 0.0210527557721095 0.0834030482863193 0.0863053576054543 0.0663123313642254 0.0352503304386915
Distortion0= 0.0636705194363818
LM0= 0.164886615306212
WordPenalty0= 0.0280548645362637
PhrasePenalty0= -0.0826622137372183
TranslationModel0= 0.0912436887313361 0.0311114860930552 0.0832146142007322 0.0372459492613214
UnknownWordPenalty0= 1
