# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.914884 on dev /home/miguel/Documentos/TA/exercices/ex4/train/development.clean.es
# We were before running iteration 4
# finished dom 25 dic 2022 12:23:10 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex4/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/mert-work/filtered/reordering-table.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.11497583043777 0.0248743346716823 0.101727845391463 0.0979531878076314 0.0625501637544083 0.0284750076417726
Distortion0= 0.0638186643117355
LM0= 0.162185252737731
WordPenalty0= 0.0298858252174826
PhrasePenalty0= -0.0751869567238727
TranslationModel0= 0.0896065679341416 0.0300788253612969 0.0837828746884803 0.0348986633205323
UnknownWordPenalty0= 1
