# MERT optimized configuration
# decoder /home/miguel/Documentos/TA/mosesdecoder/bin/moses
# BLEU 0.91589 on dev /home/miguel/Documentos/TA/exercices/ex4/train/development.clean.es
# We were before running iteration 5
# finished dom 25 dic 2022 12:23:43 CET
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/miguel/Documentos/TA/exercices/ex4/mert-work/filtered/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/mert-work/filtered/reordering-table.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/miguel/Documentos/TA/exercices/ex4/train/model.lm order=3

# dense weights for feature functions
[weight]

LexicalReordering0= 0.125201653546915 0.0303756181729943 0.103162056957622 0.0882501774453859 0.0584148054574809 0.0269440917866377
Distortion0= 0.0648102799899391
LM0= 0.159919546501956
WordPenalty0= 0.0260466948219604
PhrasePenalty0= -0.0828261585965031
TranslationModel0= 0.0858615229907817 0.0320269537576664 0.0804103840476546 0.035750055926502
UnknownWordPenalty0= 1
